version: '3'
services:
  web:
    image: filtering-matches-web:latest
    build: .
    expose:
      - 4200
    ports:
      - 4200:80
    healthcheck:
      test: "curl -f http://web"
      interval: .30s
      timeout: 10s
      retries: 3
